version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    working_directory: ~/Heat-Check-BE
    docker:
      - image: circleci/ruby:2.7.4
        environment:
          PGHOST: localhost
          PGUSER: Heat-Check-BE
          RAILS_ENV: test
      - image: postgres:14.4
        environment:
          POSTGRES_USER: Heat-Check-BE
          POSTGRES_DB: Heat-Check-BE_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Heat-Check-BE
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec

workflows:
  build-workflow:
    jobs:
      - build

  heroku-workflow:
    jobs:
      - heroku/deploy-via-git:
          force: true 
          app-name: heatcheck-be
          api-key: HEROKU_API_KEY
          branch: main